language: csharp
solution: PassSharp.sln
script:
  - xbuild /p:Configuration=Release PassSharp.sln
  - mono ./packages/Machine.Specifications.Runner.Console.0.9.2/tools/mspec-x86-clr4.exe ./src/test/bin/Release/Test.dll