version: '1.0.{build}-{branch}'
before_build:
  - nuget restore
build:
  project: PassSharp.sln
  publish_nuget: true
cache:
  - packages -> **\packages.config
deploy:
- provider: NuGet
  api_key:
    secure: NzqoRXcIEgz85NVKo/Z5MJwOVq/Sew2HRITWGmoSgpkmSv1uLfOXXcMSz2moTdkw
  skip_symbols: true
  on:
    branch: master
    appveyor_repo_tag: true