version: '1.0.{build}-{branch}'
before_build:
  - nuget restore
build:
  project: PassSharp.sln
  publish_nuget: true
cache:
  - packages -> **\packages.config
deploy:
  provider: Nuget
  skip_symbols: true
  api_key:
    secure: sTIUYo5eceC1Ui12zv2UFsCcjVfFvC9fACPz/PAODrM6Z+UYuTZkIs56uodBNA6r
  on:
    branch: master
    appveyor_repo_tag: true